version: latest

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smartmirror
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data